language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - hhvm

env:
  - WP_VERSION=master
  - WP_VERSION=4.2

matrix:
  # Nice-to-haves for right now, but not worth considering the build "broken"
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install
  - bash bin/install-package-tests.sh
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter
  - ./vendor/bin/phpcs

cache:
  directories:
    - vendor/

notifications:
  email: false