language: php

php:
  - 5.4
  - 5.5
  - 7.0

env:
  - WP_VERSION=master
  - WP_VERSION=4.2

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter

cache:
  directories:
    - vendor/

notifications:
  email: false