language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - hhvm

env:
  - WP_VERSION=master
  - WP_VERSION=4.2
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml

matrix:
  # Nice-to-haves for right now, but not worth considering the build "broken"
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install
  - bash ./bin/install-package-tests.sh
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter
  - ./vendor/bin/phpcs
  - ./vendor/bin/behat

cache:
  directories:
    - vendor/

notifications:
  email: false